return {
	settings = {
		python = {
			analysis = {
				typeCheckingMode = "off",
        reportMissingImports = "error",
        reportUndefinedVariable = "error",
        reportAssertAlwaysTrue = "error",
        reportInvalidStringEscapeSequence = "error",
        reportInvalidTypeVarUse = "error",
        reportSelfClsParameterName = "error",
        reportUnsupportedDunderAll = "error",
        reportUnusedExpression = "error",
        reportOptionalSubscript = "error",
        reportOptionalMemberAccess = "error",
        reportOptionalCall = "error",
        reportOptionalIterable = "error",
        reportOptionalContextManager = "error",
        reportOptionalOperand = "error",
        reportTypedDictNotRequiredAccess = "error",
        reportPrivateImportUsage = "error",
        reportUnboundVariable = "error",
        reportUnusedCoroutine = "error",
        reportConstantRedefinition = "error",
        reportDeprecated = "error",
        reportDuplicateImport = "error",
        reportFunctionMemberAccess = "error",
        reportImportCycles = "error",
        reportIncompatibleMethodOverride = "error",
        reportIncompatibleVariableOverride = "error",
        reportInconsistentConstructor = "error",
        reportMatchNotExhaustive = "error",
        reportMissingParameterType = "error",
        reportMissingTypeArgument = "error",
        reportOverlappingOverload = "error",
        reportPrivateUsage = "error",
        reportShadowedImports = "error",
        reportTypeCommentUsage = "error",
        reportUnknownArgumentType = "error",
        reportUnknownLambdaType = "error",
        reportUnknownMemberType = "error",
        reportUnknownParameterType = "error",
        reportUnknownVariableType = "error",
        reportUnnecessaryCast = "error",
        reportUnnecessaryComparison = "error",
        reportUnnecessaryContains = "error",
        reportUnnecessaryIsInstance = "error",
        reportUnusedClass = "error",
        reportUnusedImport = "error",
        reportUnusedFunction = "error",
        reportUntypedBaseClass = "error",
        reportUntypedClassDecorator = "error",
        reportUntypedFunctionDecorator = "error",
        reportUntypedNamedTuple = "error",
			},
		},
	},
}
