export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_RUNTIME_DIR=$HOME/.run
export XDG_STATE_HOME=$HOME/.local/state

# Cabal
export CABAL_CONFIG="$XDG_CONFIG_HOME"/cabal/config
export CABAL_DIR="$XDG_DATA_HOME"/cabal
# Conda
export CONDARC="$XDG_CONFIG_HOME"/conda/condarc
# Docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
# Gem
export GEM_HOME="$XDG_DATA_HOME"/gem
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem
# Ghcup
export GHCUP_USE_XDG_DIRS=true
# Go
export GOPATH="$XDG_DATA_HOME"/go
# Jupyter
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
# Leiningen
export LEIN_HOME="$XDG_DATA_HOME"/lein
# Less
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
# Mysql
export MYSQL_HISTFILE="$XDG_DATA_HOME"/mysql_history
# Ncurses
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo
# Nodejs
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
# NPM
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/config
# NuGet
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
# Nvm
export NVM_DIR="$XDG_DATA_HOME"/nvm
# Opam
export OPAMROOT="$XDG_DATA_HOME"/opam
# Pyenv
export PYENV_ROOT="$XDG_DATA_HOME"/pyenv
# Pylint
export PYLINTHOME="$XDG_CACHE_HOME"/pylint
# Poetry
export POETRY_HOME="$XDG_DATA_HOME"/poetry
# Pyenv
export PYENV_ROOT="$XDG_DATA_HOME"/pyenv
# Ruby bundle
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle
# Rust cargo
export CARGO_HOME="$XDG_DATA_HOME"/cargo
# Rustup
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
# Zsh
export HISTFILE="$XDG_STATE_HOME"/zsh/history
